coverage:
  status:
    project:
      default:
        threshold: 1%
codecov:
  notify:
    after_n_builds: 2
comment:
  layout: "diff"
  behavior: once
  require_changes: true
  require_base: yes
  require_head: yes
  after_n_builds: 2
  branches:
    - "master"
fixes:
  - "/opt/conda/lib/python3.8/site-packages/::project/"
  - "C:/Users/circleci/project/build/win_tmp/build/::project/"
ignore:
  - "caffe2"
  - "third_party"
