      # PyTorch Mobile PR builds (use linux host toolchain + mobile build options)
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_mobile_build
          requires:
            - setup
          build_environment: "pytorch-linux-xenial-py3-clang5-mobile-build"
          build_only: "1"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_mobile_custom_build_static
          requires:
            - setup
          build_environment: "pytorch-linux-xenial-py3-clang5-mobile-custom-build-static"
          build_only: "1"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_mobile_custom_build_dynamic
          requires:
            - setup
          build_environment: "pytorch-linux-xenial-py3-clang5-mobile-custom-build-dynamic"
          build_only: "1"
          # Use LLVM-DEV toolchain in android-ndk-r19c docker image
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
      - pytorch_linux_build:
          name: pytorch_linux_xenial_py3_clang5_mobile_code_analysis
          requires:
            - setup
          # Most of this CI is already covered by "mobile-custom-build-dynamic" job
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          build_environment: "pytorch-linux-xenial-py3-clang5-mobile-code-analysis"
          build_only: "1"
          # Use LLVM-DEV toolchain in android-ndk-r19c docker image
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
