      - pytorch_linux_test:
          name: pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test
          requires:
            - setup
            - pytorch_linux_xenial_py3_6_gcc5_4_build
          build_environment: "pytorch-linux-xenial-py3.6-gcc5.4-ge_config_legacy-test"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-gcc5.4:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
          resource_class: large
      - pytorch_linux_test:
          name: pytorch_linux_xenial_py3_6_gcc5_4_ge_config_profiling_test
          requires:
            - setup
            - pytorch_linux_xenial_py3_6_gcc5_4_build
          build_environment: "pytorch-linux-xenial-py3.6-gcc5.4-ge_config_profiling-test"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-gcc5.4:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
          resource_class: large
      - pytorch_linux_test:
          name: pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test
          requires:
            - setup
            - pytorch_linux_xenial_py3_6_gcc5_4_build
          build_environment: "pytorch-linux-xenial-py3.6-gcc5.4-ge_config_simple-test"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-gcc5.4:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
          resource_class: large
      - pytorch_linux_test:
          name: pytorch_linux_xenial_cuda10_2_cudnn7_py3_ge_config_legacy_test
          requires:
            - setup
            - pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build
          build_environment: "pytorch-linux-xenial-cuda10.1-cudnn7-ge_config_legacy-test"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
          use_cuda_docker_runtime: "1"
          resource_class: gpu.medium
      - pytorch_linux_test:
          name: pytorch_linux_xenial_cuda10_2_cudnn7_py3_ge_config_profiling_test
          requires:
            - setup
            - pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_build
          build_environment: "pytorch-linux-xenial-cuda10.1-cudnn7-ge_config_profiling-test"
          docker_image: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda10.2-cudnn7-py3-gcc7:9a3986fa-7ce7-4a36-a001-3c9bef9892e2"
          use_cuda_docker_runtime: "1"
          resource_class: gpu.medium
